using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MoodFinder
{
    public class MoodListing
    {
        public MoodListing() { }

        public List<MoodItem> BingLiuMoodList
        {
            get
            {
                string line;
                var moods = new List<MoodItem>();
                using (var reader = File.OpenText("positive-words.txt"))
                {
                    while ((line = reader.ReadLine()) != null)
                    {
                        moods.Add(new MoodItem
                        {
                            Word = line,
                            Value = new MoodValue { Category = "Positive", Weight = 1 }
                        });
                    }
                }
                using (var reader = File.OpenText("negative-words.txt"))
                {
                    while ((line = reader.ReadLine()) != null)
                    {
                        moods.Add(new MoodItem
                        {
                            Word = line,
                            Value = new MoodValue { Category = "Negative", Weight = 1 }
                        });
                    }
                }
                return moods;
            }
        }
        public List<MoodItem> PlutchikMoodList
        {
            get
            {
                return new List<MoodItem>{
                new MoodItem{Word = "acceptance", Value = new MoodValue {Category = "", Weight = 1}},
                new MoodItem{Word = "anger", Value = new MoodValue {Category = "", Weight = 1}},
                new MoodItem{Word = "anticipation", Value = new MoodValue {Category = "", Weight = 1}},
                new MoodItem{Word = "disgust", Value = new MoodValue {Category = "", Weight = 1}},
                new MoodItem{Word = "joy", Value = new MoodValue {Category = "", Weight = 1}},
                new MoodItem{Word = "fear", Value = new MoodValue {Category = "", Weight = 1}},
                new MoodItem{Word = "sadness", Value = new MoodValue {Category = "", Weight = 1}},
                new MoodItem{Word = "surprise", Value = new MoodValue {Category = "", Weight = 1}}
                };
            }
        }
        public List<MoodItem> DrummondMoodList
        {
            get
            {
                return new List<MoodItem>{
            
            new MoodItem{   Word = "delight", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "ebulient", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "ecstatic", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "elat", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "energetic", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "enthuiatic", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "euphoric", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "excit", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "exhilarat", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "overjoy", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "thril", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "tickl pink", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "turn on", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "vibrant", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "zippy", Value = new MoodValue { Category ="Happiness", Weight = 1.5 } },
            new MoodItem{   Word = "aglow", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "buoyant", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "cheer", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "elefat", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "glee", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "happy", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "in high pirit", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "jovial", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "light-hart", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "live", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "merry", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "rid high", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "sparkl", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "up", Value = new MoodValue { Category ="Happiness", Weight = 1 } },
            new MoodItem{   Word = "contnt", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "cool", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "fine", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "genial", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "glad", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "gratify", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "keen", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "pleaant", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "plea", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "satisfy", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "serene", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "sunny", Value = new MoodValue { Category ="Happiness", Weight = 0.5 } },
            new MoodItem{   Word = "ador", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "ardent", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "cherih", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "compaat", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "crazy about", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "devot", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "dot", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "ferfent", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "idoliz", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "infatuat", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "passat", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "wild about", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "worhip", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "zealou", Value = new MoodValue { Category ="Caring", Weight = 1.5 } },
            new MoodItem{   Word = "admir", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "affectate", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "attach", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "fond", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "fond of", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "huggy", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "kind", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "kind-hart", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "lov", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "partial", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "soft on", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "sympathtic", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "tend", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "trut", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "warm-hart", Value = new MoodValue { Category ="Caring", Weight = 1 } },
            new MoodItem{   Word = "apprciatif", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "attentife", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "conidat", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "friend", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "interet in", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "kind", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "like", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "respect", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "thought", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "tolerant", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "warm toward", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "yield", Value = new MoodValue { Category ="Caring", Weight = 0.5 } },
            new MoodItem{   Word = "alienat", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "barrn", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "beaten", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "bleak", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "blee", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "deject", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "depree", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "desolate", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "despondent", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "dismal", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "empty", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "gloomy", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "grief", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "grim", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "hopele", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "in dpair", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "woeful", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "worry", Value = new MoodValue { Category ="Depression", Weight = 1.5 } },
            new MoodItem{   Word = "awful", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "blue", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "cretfalen", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "demoraliz", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "devalu", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "discourag", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "dispirit", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "distrs", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "downcat", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "downhart", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "fed up", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "lost", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "melancho", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "miser", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "regret", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "rottn", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "sorrow", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "tear", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "upset", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "weepy", Value = new MoodValue { Category ="Depression", Weight = 1 } },
            new MoodItem{   Word = "blah", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "disapoint", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "down", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "funk", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "glum", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "low", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "moody", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "moro", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "somb", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "subdu", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "uncomfort", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "unhapy", Value = new MoodValue { Category ="Depression", Weight = 0.5 } },
            new MoodItem{   Word = "blemih", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "blotch", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "brokn", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "cripl", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "damag", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "fale", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "feeble", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "finih", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "flaw", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "helple", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "impotnt", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "inferior", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "invalid", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "powerle", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "useles", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "wash up", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "whip", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "worthl", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "zero", Value = new MoodValue { Category ="Inadequateness", Weight = 1.5 } },
            new MoodItem{   Word = "ail", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "defeat", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "deficient", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "dopey", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "feeble", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "helple", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "impair", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "imperfect", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "incap", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "incomptnt", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "incomplt", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "ineffectife", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "inept", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "insignificant", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "lack", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "lame", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "overwhelm", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "smal", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "substandard", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "unimportant", Value = new MoodValue { Category ="Inadequateness", Weight = 1 } },
            new MoodItem{   Word = "dry", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "incomplt", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "meag", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "puny", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "tenuou", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "tiny", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "uncertain", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "unconfinc", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "unsur", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "weak", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "wish", Value = new MoodValue { Category ="Inadequateness", Weight = 0.5 } },
            new MoodItem{   Word = "alarm", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "appal", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "despate", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "distrs", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "frightn", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "horrify", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "intimidat", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "panicky", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "paraz", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "petrify", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "shock", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "terrify", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "terror-tricken", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "wreck", Value = new MoodValue { Category ="Fear", Weight = 1.5 } },
            new MoodItem{   Word = "afraid", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "apprhnif", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "awkward", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "defenife", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "fear", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "fidgty", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "fret", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "jumpy", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "nerfou", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "scar", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "shaky", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "skitish", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "spinls", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "taut", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "threaten", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "troubl", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "wire", Value = new MoodValue { Category ="Fear", Weight = 1 } },
            new MoodItem{   Word = "anxiou", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "care", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "cautiou", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "disquit", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "gooe-bumpy", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "shy", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "tene", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "timid", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "uneay", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "unsur", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "watch", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "worry", Value = new MoodValue { Category ="Fear", Weight = 0.5 } },
            new MoodItem{   Word = "baffl", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "befudl", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "chaotic", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "confound", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "confu", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "dizzy", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "flut", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "rattl", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "reel", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "shock", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "shook up", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "speechles", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "startl", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "stump", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "stun", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "taken-aback", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "thrown", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "thundtruck", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "trap", Value = new MoodValue { Category ="Confusion", Weight = 1.5 } },
            new MoodItem{   Word = "adrift", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "ambifalnt", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "bewild", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "puzzl", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "blur", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "disconct", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "disord", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "disorganiz", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "disquit", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "disturb", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "foggy", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "frutrat", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "misl", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "mistakn", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "misundstood", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "mixe up", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "perplex", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "troubl", Value = new MoodValue { Category ="Confusion", Weight = 1 } },
            new MoodItem{   Word = "distract", Value = new MoodValue { Category ="Confusion", Weight = 0.5 } },
            new MoodItem{   Word = "uncertain", Value = new MoodValue { Category ="Confusion", Weight = 0.5 } },
            new MoodItem{   Word = "uncomfort", Value = new MoodValue { Category ="Confusion", Weight = 0.5 } },
            new MoodItem{   Word = "undecid", Value = new MoodValue { Category ="Confusion", Weight = 0.5 } },
            new MoodItem{   Word = "unsetl", Value = new MoodValue { Category ="Confusion", Weight = 0.5 } },
            new MoodItem{   Word = "unsur", Value = new MoodValue { Category ="Confusion", Weight = 0.5 } },
            new MoodItem{   Word = "abue", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "ach", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "anguih", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "cruh", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "degrad", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "destroy", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "devatat", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "discard", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "disgrac", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "forakn", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "humiliat", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "mock", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "punih", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "reject", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "ridicul", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "ruin", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "scorn", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "stabb", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "tortur", Value = new MoodValue { Category ="Hurt", Weight = 1.5 } },
            new MoodItem{   Word = "annoy", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "belitl", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "cheapen", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "criticiz", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "damag", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "depreciat", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "devalu", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "discrit", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "distrs", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "impair", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "injur", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "malign", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "marr", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "miff", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "mistrat", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "resent", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "troubl", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "used", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "wound", Value = new MoodValue { Category ="Hurt", Weight = 1 } },
            new MoodItem{   Word = "let down", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "minimiz", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "neglect", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "put away", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "put down", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "rueful", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "tend", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "touch", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "unhapy", Value = new MoodValue { Category ="Hurt", Weight = 0.5 } },
            new MoodItem{   Word = "affront", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "belligent", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "bitt", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "burn up", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "enrag", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "fum", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "furiou", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "heat", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "incen", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "infuriat", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "intene", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "outrag", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "profok", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "seeth", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "storm", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "truculnt", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "venge", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "vindictiv", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "wild", Value = new MoodValue { Category ="Anger", Weight = 1.5 } },
            new MoodItem{   Word = "aggrafat", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "annoy", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "antagonitic", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "crabby", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "cranky", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "exapat", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "fum", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "grouchy", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "hostil", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "ill-tmp", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "indignant", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "irat", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "irritat", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "offend", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "ratty", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "resent", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "sore", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "spit", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "testy", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "tick off", Value = new MoodValue { Category ="Anger", Weight = 1 } },
            new MoodItem{   Word = "bugg", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "chagrin", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "dismay", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "gall", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "grim", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "impatint", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "irke", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "petulant", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "resent", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "sulln", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "uptight", Value = new MoodValue { Category ="Anger", Weight = 0.5 } },
            new MoodItem{   Word = "abandon", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "black", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "cut off", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "desert", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "destroy", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "empty", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "forakn", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "isolat", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "maroon", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "neglect", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "ostraciz", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "outcat", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "reject", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "shun", Value = new MoodValue { Category ="Loneliness", Weight = 1.5 } },
            new MoodItem{   Word = "alienat", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "alon", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "apart", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "cheerle", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "companl", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "deject", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "despondent", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "estrang", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "exclud", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "left out", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "leftof", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "lone", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "oppr", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "unchih", Value = new MoodValue { Category ="Loneliness", Weight = 1 } },
            new MoodItem{   Word = "blue", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "detach", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "discourag", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "distant", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "insulat", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "melancho", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "remote", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "separate", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "withdrawn", Value = new MoodValue { Category ="Loneliness", Weight = 0.5 } },
            new MoodItem{   Word = "abah", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "deba", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "degrad", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "delinquent", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "depraf", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "disgrac", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "evil", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "expo", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "humiliat", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "judg", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "mortify", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "sham", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "sinful", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "wick", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "wrong", Value = new MoodValue { Category ="Remorse", Weight = 1.5 } },
            new MoodItem{   Word = "apologtic", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "asham", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "contrit", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "culp", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "demean", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "downhart", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "flut", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "guilty", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "penitent", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "regret", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "remore", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "repentant", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "shamfac", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "sorrow", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "sorry", Value = new MoodValue { Category ="Remorse", Weight = 1 } },
            new MoodItem{   Word = "bash", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "bluh", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "chagrin", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "chatn", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "cretfalen", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "embara", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "hesitant", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "humbl", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "meek", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "regret", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "reluctant", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
            new MoodItem{   Word = "sheepish", Value = new MoodValue { Category ="Remorse", Weight = 0.5 } },
    
            };


            }
        }
    }
    public class MoodItem
    {
        public string Word { get; set; }
        public MoodValue Value { get; set; }
       
    }
    public class MoodValue
    {
        public string Category { get; set; }
        public double Weight { get; set; }
    }
}
