//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tweet
    {
        public string C_id { get; set; }
        public string id_str { get; set; }
        public string text { get; set; }
        public string retweeted { get; set; }
        public string screen_name { get; set; }
        public Nullable<int> followers_count { get; set; }
        public string match_key_1 { get; set; }
        public string match_text_1 { get; set; }
        public string match_cat_1 { get; set; }
        public string match_key_2 { get; set; }
        public string match_text_2 { get; set; }
        public string match_cat_2 { get; set; }
        public string match_key_3 { get; set; }
        public string match_text_3 { get; set; }
        public string match_cat_3 { get; set; }
        public string match_key_4 { get; set; }
        public string match_text_4 { get; set; }
        public string match_cat_4 { get; set; }
        public string match_key_5 { get; set; }
        public string match_text_5 { get; set; }
        public string match_cat_5 { get; set; }
        public string match_key_6 { get; set; }
        public string match_text_6 { get; set; }
        public string match_cat_6 { get; set; }
        public string mood_name_1 { get; set; }
        public Nullable<decimal> mood_value_1 { get; set; }
        public string mood_name_2 { get; set; }
        public Nullable<decimal> mood_value_2 { get; set; }
        public string mood_name_3 { get; set; }
        public Nullable<decimal> mood_value_3 { get; set; }
        public string mood_name_4 { get; set; }
        public Nullable<decimal> mood_value_4 { get; set; }
        public string mood_name_5 { get; set; }
        public Nullable<decimal> mood_value_5 { get; set; }
        public string mood_name_6 { get; set; }
        public Nullable<decimal> mood_value_6 { get; set; }
        public string mood_name_7 { get; set; }
        public Nullable<decimal> mood_value_7 { get; set; }
        public string mood_name_8 { get; set; }
        public Nullable<decimal> mood_value_8 { get; set; }
        public string mood_name_9 { get; set; }
        public Nullable<decimal> mood_value_9 { get; set; }
        public string mood_name_10 { get; set; }
        public Nullable<decimal> mood_value_10 { get; set; }
        public Nullable<long> time { get; set; }
        public string utc_date { get; set; }
        public Nullable<int> utc_year { get; set; }
        public Nullable<int> utc_month { get; set; }
        public Nullable<int> utc_day { get; set; }
        public Nullable<int> utc_hours { get; set; }
        public Nullable<int> utc_minutes { get; set; }
        public Nullable<int> nm_utc_year { get; set; }
        public Nullable<int> nm_utc_month { get; set; }
        public Nullable<int> nm_utc_day { get; set; }
        public Nullable<int> nm_utc_hours { get; set; }
        public Nullable<int> nm_utc_minutes { get; set; }
        public Nullable<int> bing_positive { get; set; }
        public Nullable<int> bing_negative { get; set; }
        public string id { get; set; }
        public long pmid { get; set; }
    }
}
