//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculations
{
    using System;
    using System.Collections.Generic;
    
    public partial class analysis
    {
        public long pid { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> hours { get; set; }
        public Nullable<int> minutes { get; set; }
        public string symbol { get; set; }
        public Nullable<int> total_tweets { get; set; }
        public Nullable<decimal> start_price { get; set; }
        public Nullable<decimal> start_volume { get; set; }
        public Nullable<decimal> total_mood_1 { get; set; }
        public Nullable<decimal> total_mood_2 { get; set; }
        public Nullable<decimal> total_mood_3 { get; set; }
        public Nullable<decimal> total_mood_4 { get; set; }
        public Nullable<decimal> total_mood_5 { get; set; }
        public Nullable<decimal> total_mood_6 { get; set; }
        public Nullable<decimal> total_mood_7 { get; set; }
        public Nullable<decimal> total_mood_8 { get; set; }
        public Nullable<decimal> total_mood_9 { get; set; }
        public Nullable<decimal> total_mood_10 { get; set; }
        public Nullable<decimal> bing_positive { get; set; }
        public Nullable<decimal> bing_negative { get; set; }
        public string change_in_percent { get; set; }
        public string @class { get; set; }
    }
}
